-- Registra tabelas/colunas presentes no banco mas ausentes nas migrations.
-- Escopo: create table + colunas basicas (PK, defaults essenciais).

create table if not exists public.acidente_partes_grupo (
  id uuid not null default gen_random_uuid(),
  nome text,
  ativo boolean default true,
  criado_em timestamptz not null default now(),
  constraint acidente_partes_grupo_pkey primary key (id)
);

create table if not exists public.acidente_partes_sub_grupo (
  id uuid not null default gen_random_uuid(),
  nome text,
  ativo boolean default true,
  criado_em timestamptz not null default now(),
  grupo_id uuid,
  constraint acidente_partes_sub_grupo_pkey primary key (id)
);

create table if not exists public.caracteristica_epi (
  id uuid not null default gen_random_uuid(),
  caracteristica_material text not null,
  ativo boolean default true,
  constraint caracteristica_epi_pkey primary key (id)
);

create table if not exists public.centros_estoque (
  id uuid not null default gen_random_uuid(),
  almox text,
  centro_custo uuid,
  created_at timestamptz not null default now(),
  ativo boolean default true,
  account_owner_id uuid not null default public.my_owner_id(),
  constraint centros_estoque_pkey primary key (id)
);

create table if not exists public.cor (
  id uuid not null default gen_random_uuid(),
  cor text not null,
  ativo boolean default true,
  constraint cor_pkey primary key (id)
);

create table if not exists public.edge_functions_error_report (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  function_name text not null,
  bucket text not null,
  retention_days integer not null,
  cutoff timestamptz not null,
  dry_run boolean not null,
  total_listed integer not null,
  candidates integer not null,
  deleted integer not null,
  errors_count integer not null,
  duration_ms integer,
  details jsonb,
  http_status integer,
  error_message text,
  error_stack text,
  sb_request_id text,
  constraint edge_functions_error_report_pkey primary key (id)
);

create table if not exists public.entrada_historico (
  id uuid not null default gen_random_uuid(),
  material_id uuid,
  material_ent jsonb,
  created_at timestamptz not null default now(),
  "usuarioResponsavel" uuid,
  entrada_id uuid,
  account_owner_id uuid not null default public.my_owner_id(),
  constraint entrada_historico_pkey primary key (id)
);

create table if not exists public.epi_classe (
  id uuid not null default gen_random_uuid(),
  class_epi text not null,
  ativo boolean default true,
  constraint epi_classe_pkey primary key (id)
);

create table if not exists public.fabricantes (
  id uuid not null default gen_random_uuid(),
  fabricante text not null,
  ativo boolean default true,
  account_owner_id uuid not null default public.my_owner_id(),
  constraint fabricantes_pkey primary key (id)
);

create table if not exists public.material_grupo_caracteristica_epi (
  id uuid not null default gen_random_uuid(),
  material_id uuid not null,
  grupo_caracteristica_epi uuid not null,
  account_owner_id uuid not null,
  created_at timestamptz default now(),
  constraint material_grupo_caracteristica_epi_pkey primary key (id)
);

create table if not exists public.material_grupo_cor (
  id uuid not null default gen_random_uuid(),
  material_id uuid not null,
  grupo_material_cor uuid not null,
  account_owner_id uuid not null,
  created_at timestamptz default now(),
  constraint material_grupo_cor_pkey primary key (id)
);

create table if not exists public.medidas_calcado (
  id uuid not null default gen_random_uuid(),
  numero_calcado text not null,
  ativo boolean default true,
  constraint medidas_calcado_pkey primary key (id)
);

create table if not exists public.medidas_vestimentas (
  id uuid not null default gen_random_uuid(),
  medidas text not null,
  ativo boolean default true,
  constraint medidas_vestimentas_pkey primary key (id)
);

create table if not exists public.permissions (
  id uuid not null default gen_random_uuid(),
  key text not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint permissions_pkey primary key (id)
);

create table if not exists public.role_permissions (
  role_id uuid not null,
  permission_id uuid not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint role_permissions_pkey primary key (role_id, permission_id)
);

create table if not exists public.roles (
  id uuid not null default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint roles_pkey primary key (id)
);

create table if not exists public.status_saida (
  id uuid not null default gen_random_uuid(),
  status text,
  created_at timestamptz not null default now(),
  ativo boolean default true,
  constraint status_saida_pkey primary key (id)
);

create table if not exists public.user_permission_overrides (
  user_id uuid not null,
  permission_key text not null,
  allowed boolean not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_permission_overrides_pkey primary key (user_id, permission_key)
);

create table if not exists public.user_roles (
  user_id uuid not null,
  role_id uuid not null,
  scope_parent_user_id uuid not null default '00000000-0000-0000-0000-000000000000'::uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_roles_pkey primary key (user_id, role_id, scope_parent_user_id)
);

-- Garantia de colunas criadas manualmente em tabelas existentes.
alter table if exists public.material_grupo_cor
  add column if not exists created_at timestamptz default now();

alter table if exists public.material_grupo_caracteristica_epi
  add column if not exists created_at timestamptz default now();
